cal/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cal'
urlpatterns = [
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    # url(r'^event/del/(?P<event_id>\d+)/$', views.del_event, name='event_del'),

    # path('event/<int:id>', views.del_event, name='del_event')
]

urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>', views.event, name='event_edit'),
    path('event/del/<int:event_id>', views.del_event, name='event_del'),
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),
    path('cross/<int:id>', views.cross, name='cross'),
    path('uncross/<int:id>', views.uncross, name='uncross'),
    path('<int:id>/', views.delete, name='delete'),
    path('logout/', views.signout, name="logout")
]

expensetracker/urls.py
from django.urls import path
from . import views
app_name = 'expensetracker'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('<int:id>/', views.edit_entry, name="edit_entry"),
    path('daterange', views.date_range, name="daterange"),

]

project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('expensetracker/', include('expensetracker.urls')),
    path('todo/', include('todo.urls')),
    path('', include('cal.urls')),
    path('', include('dashboard.urls')),
    path('autho/', include('autho.urls')),
]


urlpatterns += staticfiles_urlpatterns()

dashboard/models.py
from django.db import models

# Create your models here.

expensetracker/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Expenses(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date = models.DateField()
    description = models.CharField(max_length=100, null=True)
    cost = models.CharField(max_length=30)
    notedate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

expensetracker/forms.py
from django.forms import ModelForm
from .models import Expenses

from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'


class ExpenseForm(ModelForm):
    class Meta:

        model = Expenses
        widgets = {'date': DateInput()}
        # datefield = forms.DateField(widget=DateInput)
        fields = ['date', 'description', 'cost']

dashboard/views.py
from expensetracker.models import Expenses
from todo.models import List
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.db.models import Sum
from datetime import datetime, timedelta
from todo.forms import ListForm  # Create your views here.
from django.contrib.auth import logout


def index(request):
    user = request.user
    today = datetime.now().date()
    now = datetime.now()
    dt_string = now.strftime("%H:%M:%S")

    yesterday = today - timedelta(1)
    seven = today - timedelta(7)
    thirty = today - timedelta(30)
    year = today - timedelta(365)
    tc = Expenses.objects.filter(date=today).aggregate(Sum('cost'))
    yc = Expenses.objects.filter(date=yesterday).aggregate(Sum('cost'))
    sc = Expenses.objects.filter(
        date__gte=seven, date__lte=today).aggregate(Sum('cost'))
    thc = Expenses.objects.filter(
        date__gte=thirty, date__lte=today).aggregate(Sum('cost'))
    yrc = Expenses.objects.filter(
        date__gte=year, date__lte=today).aggregate(Sum('cost'))
    entries = Expenses.objects.order_by('-notedate')

    if request.method == "POST":
        form_data = ListForm(request.POST)
        if form_data.is_valid():
            form_data.save()

    todo_list = List.objects.all
    todo_form = ListForm()

    context = {'today': today, 'tc': tc,
               'yc': yc, "sc": sc, "thc": thc, 'yrc': yrc, "entries": entries, 'dt_string': dt_string, "todo_list": todo_list, 'todo_form': todo_form, 'user': user}
    return render(request, 'dashboard/index.html', context)


def delete(request, id):
    entry = List.objects.get(pk=id)
    entry.delete()

    return redirect('dashboard:index')


def cross(request, id):
    item = List.objects.get(pk=id)
    item.completed = True
    item.save()
    return redirect('dashboard:index')


def uncross(request, id):
    item = List.objects.get(pk=id)
    item.completed = False
    item.save()
    return redirect('dashboard:index')


def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('autho:signin'))

expensetracker/views.py
from django.contrib import messages
from django.shortcuts import render
from .models import Expenses
from .forms import ExpenseForm
from django.urls import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.db.models import Sum
from datetime import datetime, timedelta

# Create your views here.

# display and add expenses


def dashboard(request):
    if request.method == "POST":
        form_data = ExpenseForm(request.POST)
        if form_data.is_valid():
            form_data.save()
            messages.success(request, "successfully added Entry.")
        else:
            messages.error(request, "Entry Submission was unsuccesful.")
    entries = Expenses.objects.order_by('-notedate')
    form = ExpenseForm()
    context = {'entries': entries, "form": form}
    today = datetime.now().date()

    yesterday = today - timedelta(1)
    seven = today - timedelta(7)
    thirty = today - timedelta(30)
    year = today - timedelta(365)

    tc = Expenses.objects.filter(date=today).aggregate(Sum('cost'))

    yc = Expenses.objects.filter(date=yesterday).aggregate(Sum('cost'))

    sc = Expenses.objects.filter(
        date__gte=seven, date__lte=today).aggregate(Sum('cost'))

    thc = Expenses.objects.filter(
        date__gte=thirty, date__lte=today).aggregate(Sum('cost'))
    yrc = Expenses.objects.filter(
        date__gte=year, date__lte=today).aggregate(Sum('cost'))

    context = {'today': today, 'tc': tc,
               'yc': yc, "sc": sc, "thc": thc, 'yrc': yrc, 'form': form, "entries": entries}

    return render(request, "expensetracker/dashboard.html", context)


def edit_entry(request, id):
    entry = Expenses.objects.get(pk=id)
    if request.GET.get("del") == "true":
        entry.delete()
        return HttpResponseRedirect(reverse("expensetracker:dashboard"))
    elif request.method == "POST":
        form_data = ExpenseForm(request.POST, instance=entry)
        if form_data.is_valid():
            form_data.save()
            return HttpResponseRedirect(reverse("expensetracker:dashboard", args=(entry.id,)))

    form_instance = ExpenseForm(instance=entry)

    context = {'form_instance': form_instance, "entry": entry}
    return render(request, 'expensetracker/dashboard.html', context)


def date_range(request):
    if request.method == "POST":
        fd = request.POST['fromdate']
        td = request.POST['todate']

        expense = Expenses.objects.filter(
            Q(date__gte=fd) & Q(date__lte=td)).values('date').annotate(totaldaily=Sum('cost'))

        expense_count = Expenses.objects.filter(
            Q(date__gte=fd) & Q(date__lte=td)).count()

        expense_total = Expenses.objects.filter(
            Q(date__gte=fd) & Q(date__lte=td)).values('date').annotate(totaldaily=Sum('cost')).aggregate(Sum('totaldaily'))

        context = {'fd': fd, "td": td, "expense": expense,
                   "expense_count": expense_count, "expense_total": expense_total}
        return render(request, "expensetracker/range.html", context)
    return render(request, "expensetracker/range.html")

expensetracker/templates/expensetracker/base.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>
    {%block title%}
    {%endblock%}

  </title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/exp.css' %}">
</head>

<body>

  <div class="container-fluid">
    <div class="row ">
      <div class=" main-sidebar-cont col-sm-2 min-vh-100">
        {% block sidebar %}
        <div class="branding">
          <h2> <a href="/">Pro-Ductive</a> </h2>
        </div>
        <ul class="sidebar-nav">
          <li class="nav-item"><a href="/diary">My Diary</a></li>
        </ul>
        <ul class="sidebar-nav">
          <li class="nav-item"><a href="/expensetracker">Expense Tracker</a></li>
        </ul>
        <ul class="sidebar-nav">
          <li class="nav-item"><a href="/calendar">Events Calender</a></li>
        </ul>


        {% endblock %}

      </div>
      <div class="content-cont col-sm-10 ">{% block body %}{% endblock %}</div>
    </div>
  </div>


  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>

expensetracker/templates/expensetracker/dashboard.html
{% extends 'expensetracker/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<!-- http://127.0.0.1:8000/expensetracker/dashboard-->
{%block body%}
<div class="expense-header">
  <h1 style="font-family: 'Space Mono', monospace; margin: 20px 10px;font-weight: 700;">Expense Tracker</h1>

  <a class="date-range" href="daterange">View By Date</a>
</div>




<div class="data-display">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Today's Expenses</h4>
      <h5>${{tc.cost__sum}}</h5>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Yesterday's Expenses</h4>
      <h5>${{yc.cost__sum}}</h5>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Last 7 Days Expenses</h4>
      <h5>${{sc.cost__sum}}</h5>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Last 30 Days Expenses</h4>
      <h5>${{thc.cost__sum}}</h5>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Last 1 Year's Expenses</h4>
      <h5>${{yrc.cost__sum}}</h5>
    </div>
  </div>
</div>




<!-- <button> <a href="all">View all Entries</a></button>
<button> <a href='daterange'>View by date range</a></button> -->



<div>
  <div class="add-expense" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add Expenses
  </div>

</div>


<table class="table table-bordered table-light">
  <thead>
    <tr>
      <th class="text-center" scope="col">S/N</th>
      <th class="text-center" scope="col">Expense Description</th>
      <th class="text-center" scope="col">Expense Cost($)</th>
      <th class="text-center" scope="col">Expense Date</th>
      <th class="text-center" scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {%for entry in entries%}
    <tr>
      <th class="text-center" scope="row">{{forloop.counter}}</th>
      <td class="text-center">{{entry.description}}</td>
      <td class="text-center">{{entry.cost}}</td>
      <td class="text-center">{{entry.date}}</td>
      <td class="text-center" scope="col">

        <a href="{% url 'expensetracker:edit_entry' entry.id %}?del=true">Delete</a>
      </td>
    </tr>
    {%endfor%}
  </tbody>
</table>




<!-- Add Expense Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create New Expense Entry</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <h1>Add Expenses</h1>
      <div class="exp-form">
        <form action="{% url 'expensetracker:dashboard' %}" method="POST">
          {% csrf_token %}
          {{ form | crispy }}
          <button type="submit" class="btn btn-block btn-primary">Add</button>
        </form>
      </div>


    </div>
  </div>
</div>
{%endblock%}

expensetracker/templates/expensetracker/index.html
{% extends 'expensetracker/base.html' %}
{% load crispy_forms_tags %}

<!-- the whole display of entries will be placed in a tabel format -->

{%block body%}
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add Expenses
</button>
<button><a href="daterange">View By Date</a></button>


<table class="table table-light">
  <thead>
    <tr>
      <th scope="col">S/N</th>
      <th scope="col">Expense Description</th>
      <th scope="col">Expense Cost</th>
      <th scope="col">Expense Date</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {%for entry in entries%}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{entry.description}}</td>
      <td>{{entry.cost}}</td>
      <td>{{entry.date}}</td>
      <td scope="col">

        <a href="{% url 'expensetracker:edit_entry' entry.id %}?del=true">Delete</a>
      </td>
    </tr>
    {%endfor%}
  </tbody>
</table>




<!-- Add Expense Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create New Expense Entry</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <h1>Add Expenses</h1>
      <form action="{% url 'expensetracker:index' %}" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-block btn-primary">Add</button>
      </form>

    </div>
  </div>
</div>
{%endblock%}

expensetracker/templates/expensetracker/range.html
{% extends 'expensetracker/base.html' %}

<!-- http://127.0.0.1:8000/expensetracker/daterange -->
{% block body%}
<div>
  <div type="button" class="sel-date-range" data-bs-toggle="modal" data-bs-target="#rangeModal">
    Select Date Range
  </div>
</div>


<div class="modal fade" id="rangeModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title cdr" id="exampleModalLabel">Choose Date Range</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="range-form">
        <form method="POST" action="">
          {%csrf_token%}
          <div class="form-group">
            <label>Start Date</label>
            <input class="form-control" type="date" id="fromdate" name="fromdate" required='true'>
          </div>
          <div class="form-group">
            <label>End Date</label>
            <input class="form-control" type="date" id="todate" name="todate" required='true'>
          </div>
          <div>
            <button class="btn" type="submit" name="submit">Submit</button>
          </div>
        </form>
      </div>

    </div>
  </div>
</div>



<div class="date-range-display">
  <h5>The dates selected is
    <p> </p>
    <p>from: <span class="date-disp">{{fd}}</span> </p>
    <p>to: <span class="date-disp">{{td}}</span> </p>
  </h5>
</div>

<div class="table-data-display">


  <table class="table table-bordered table-light">
    <thead>
      <tr>
        <th class="text-center" scope="col">S/N</th>
        <th class="text-center" scope="col">Expense Date</th>
        <th class="text-center" scope="col">Total Expense Cost($)</th>
      </tr>
    </thead>
    <tbody>
      {%for ex in expense%}
      <tr>
        <th class="text-center" scope="row">{{forloop.counter}}</th>
        <td class="text-center">{{ex.date}}</td>
        <td class="text-center">{{ex.totaldaily}}</td>
      </tr>
      {%endfor%}
      <td class="table-success text-start" style="font-weight: 700;" colspan="2">Grand Total</td>
      <td class="table-success text-center" style="font-weight: 700;" colspan="1">{{expense_total.totaldaily__sum}}</td>
    </tbody>
  </table>
</div>
{%endblock%}