cal/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cal'
urlpatterns = [
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    # url(r'^event/del/(?P<event_id>\d+)/$', views.del_event, name='event_del'),

    # path('event/<int:id>', views.del_event, name='del_event')
]

urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>', views.event, name='event_edit'),
    path('event/del/<int:event_id>', views.del_event, name='event_del'),
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),
    path('cross/<int:id>', views.cross, name='cross'),
    path('uncross/<int:id>', views.uncross, name='uncross'),
    path('<int:id>/', views.delete, name='delete'),
    path('logout/', views.signout, name="logout")
]

project4/project4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('expensetracker/', include('expensetracker.urls')),
    path('todo/', include('todo.urls')),
    path('', include('cal.urls')),
    path('', include('dashboard.urls')),
    path('autho/', include('autho.urls')),
]

project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('expensetracker/', include('expensetracker.urls')),
    path('todo/', include('todo.urls')),
    path('', include('cal.urls')),
    path('', include('dashboard.urls')),
    path('autho/', include('autho.urls')),
]


urlpatterns += staticfiles_urlpatterns()

todo/urls.py
from django.urls import path
from . import views
app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.delete, name='delete'),
    path('cross/<int:id>', views.cross, name='cross'),
    path('uncross/<int:id>', views.uncross, name='uncross')
]

todo/models.py
from django.db import models

# Create your models here.


class List(models.Model):
    item = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.item + ' | ' + str(self.completed)

todo/forms.py
from django import forms
from .models import List


class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['item', 'completed']

todo/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
from .models import List
from .forms import ListForm
from django.contrib import messages


# Create your views here.

def index(request):
    if request.method == "POST":
        form_data = ListForm(request.POST)
        if form_data.is_valid():
            form_data.save()

    entries = List.objects.all
    form = ListForm()
    context = {'entries': entries, 'form': form}
    return render(request, 'dashboard/index.html', context)


def delete(request, id):
    entry = List.objects.get(pk=id)
    entry.delete()
    return redirect('todo:index')


def cross(request, id):
    item = List.objects.get(pk=id)
    item.completed = True
    item.save()
    return redirect('todo:index')


def uncross(request, id):
    item = List.objects.get(pk=id)
    item.completed = False
    item.save()
    return redirect('todo:index')

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {%block title%}
    {%endblock%}

  </title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>

  {%block body%}
  {%endblock%}
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}
{% load crispy_forms_tags %}



{%block body%}


<h1>To-do List</h1>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#todoModal">
  New Entry
</button>

<!-- Modal -->
<div class="modal fade" id="todoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create New Entry</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'todo:index' %}" method="POST">
        {% csrf_token %}
        {{ form.item}}
        <button type="submit" class="btn btn-block btn-primary">Add Entry</button>
      </form>
    </div>
  </div>
</div>



<table class="table table-bordered">
  <thead>
    <tr class="table-primary">
      <th scope="col">S/N</th>
      <th scope="col">Task</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {%for entry in entries%}
    {% if entry.completed %}
    <tr class="table-success">
      <th scope="row">{{forloop.counter}}</th>
      <td>{{entry.item}}</td>
      <td> <a href="{% url 'todo:uncross' entry.id %}">Done</a> </td>
      <td><a href="{% url 'todo:delete' entry.id %}">Remove</a></td>
    </tr>
    {%else%}
    <tr class="table-danger">
      <th scope="row">{{forloop.counter}}</th>
      <td>{{entry.item}}</td>
      <td><a href="{% url 'dashboard:cross' entry.id %}">Ongoing</a></td>
      <td><a href="{% url 'dashboard:delete' entry.id %}">Remove</a></td>
    </tr>
    {%endif%}

    {%endfor%}
  </tbody>
</table>





{% endblock %}