autho/urls.py
from django.urls import path
from django.contrib.auth import views

from django.contrib import admin
from . import views

app_name = "autho"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('logout/', views.signout, name="logout"),
]

cal/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cal'
urlpatterns = [
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    # url(r'^event/del/(?P<event_id>\d+)/$', views.del_event, name='event_del'),

    # path('event/<int:id>', views.del_event, name='del_event')
]

urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>', views.event, name='event_edit'),
    path('event/del/<int:event_id>', views.del_event, name='event_del'),
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),
    path('cross/<int:id>', views.cross, name='cross'),
    path('uncross/<int:id>', views.uncross, name='uncross'),
    path('<int:id>/', views.delete, name='delete'),
    path('logout/', views.signout, name="logout")
]

project4/project4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('expensetracker/', include('expensetracker.urls')),
    path('todo/', include('todo.urls')),
    path('', include('cal.urls')),
    path('', include('dashboard.urls')),
    path('autho/', include('autho.urls')),
]

project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('expensetracker/', include('expensetracker.urls')),
    path('todo/', include('todo.urls')),
    path('', include('cal.urls')),
    path('', include('dashboard.urls')),
    path('autho/', include('autho.urls')),
]


urlpatterns += staticfiles_urlpatterns()

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from expensetracker.models import Expenses
from todo.models import List
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.db.models import Sum
from datetime import datetime, timedelta
from todo.forms import ListForm  # Create your views here.
from django.contrib.auth import logout


def index(request):
    user = request.user
    today = datetime.now().date()
    now = datetime.now()
    dt_string = now.strftime("%H:%M:%S")

    yesterday = today - timedelta(1)
    seven = today - timedelta(7)
    thirty = today - timedelta(30)
    year = today - timedelta(365)
    tc = Expenses.objects.filter(date=today).aggregate(Sum('cost'))
    yc = Expenses.objects.filter(date=yesterday).aggregate(Sum('cost'))
    sc = Expenses.objects.filter(
        date__gte=seven, date__lte=today).aggregate(Sum('cost'))
    thc = Expenses.objects.filter(
        date__gte=thirty, date__lte=today).aggregate(Sum('cost'))
    yrc = Expenses.objects.filter(
        date__gte=year, date__lte=today).aggregate(Sum('cost'))
    entries = Expenses.objects.order_by('-notedate')

    if request.method == "POST":
        form_data = ListForm(request.POST)
        if form_data.is_valid():
            form_data.save()

    todo_list = List.objects.all
    todo_form = ListForm()

    context = {'today': today, 'tc': tc,
               'yc': yc, "sc": sc, "thc": thc, 'yrc': yrc, "entries": entries, 'dt_string': dt_string, "todo_list": todo_list, 'todo_form': todo_form, 'user': user}
    return render(request, 'dashboard/index.html', context)


def delete(request, id):
    entry = List.objects.get(pk=id)
    entry.delete()

    return redirect('dashboard:index')


def cross(request, id):
    item = List.objects.get(pk=id)
    item.completed = True
    item.save()
    return redirect('dashboard:index')


def uncross(request, id):
    item = List.objects.get(pk=id)
    item.completed = False
    item.save()
    return redirect('dashboard:index')


def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('autho:signin'))

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>
    {%block title%}
    {%endblock%}

  </title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/brands.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

  <div class="container-fluid">
    <div class="row ">
      <div class=" main-sidebar-cont col-sm-2 min-vh-100">
        {% block sidebar %}
        <div class="branding">
          <h2> <a href="/">Pro-Ductive</a> </h2>
        </div>
        <ul class="sidebar-nav">
          <li class="nav-item"><a href="/diary">My Diary</a></li>
        </ul>
        <ul class="sidebar-nav">
          <li class="nav-item"><a href="/expensetracker">Expense Tracker</a></li>
        </ul>
        <ul class="sidebar-nav">
          <li class="nav-item"><a href="/calendar">Events Calender</a></li>
        </ul>
        <ul class="sidebar-nav">
          <li style="background-color: white; border-radius: 10px;" class="nav-item ">
            <a style="color: black;" class="logout" href="{% url 'autho:logout' %}">Logout</a>
          </li>
        </ul>
        {% endblock %}

      </div>
      <div class="content-cont col-sm-10 ">{% block body %}
        {% endblock %}</div>
    </div>
  </div>


  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{%block body%}
<div class="main-grid">
  <!-- ITEM ONE -- WELCOME MSG -->
  <div class="item one">
    <h1 class="welcome-msg"><i class="fas fa-door-open"></i>Welcome To ProDuctivity</h1>
    <h1>{{user}}</h1>
  </div>

  <!-- ITEM TWO --   -->
  <div class="item two">
    <div class="diary-icon">
      <h3>Journal</h3>
      <a href="/diary"><i class="fas fa-journal-whills fa-10x"></i></a>
    </div>
    <div>
      <h4>Log your daily activities in your Journal</h4>
    </div>

  </div>

  <!-- ITEM THREE -- Expense Tracker CALENDAR   -->
  <div class="item three">
    <div class="exp-header">
      <h4><i class="fas fa-wallet"></i> <a href="/expensetracker">Expense Tracker</a> </h4>
    </div>
    <div class="card">
      <div class="card-body bg-light">
        <span class="exp-head">Today's Expenses: </span>
        <span class="exp-bod">${{tc.cost__sum}}</span>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <span class="exp-head">Yesterday's Expenses: </span>
        <span class="exp-bod">${{yc.cost__sum}}</span>
      </div>
    </div>
    <div class="card">
      <div class="card-body bg-light">
        <span class="exp-head">Past 7 day's Expenses: </span>
        <span class="exp-bod">${{sc.cost__sum}}</span>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <span class="exp-head">Past 30 Day's Expenses: </span>
        <span class="exp-bod">${{thc.cost__sum}}</span>
      </div>
    </div>
    <div class="card">
      <div class="card-body bg-light">
        <span class="exp-head">Past 1 Year's Expenses: </span>
        <span class="exp-bod">${{yrc.cost__sum}}</span>
      </div>
    </div>
  </div>
  <!-- ITEM 4 -- DATE TIME -->
  <div class="item four">
    <h1><i class="fas fa-calendar-day"></i>{{today}}</h1>


  </div>
  <!-- ITEM 5 TODO-LIST -->
  <div class="item five">
    <div class="todo-header">
      <h4><i class="fas fa-check-square"></i>To-Do List</h4>
      <button class="todo-btn" data-bs-toggle="modal" data-bs-target="#todoModal">
        New Entry
      </button>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr class="table-primary">
          <th class="text-center" scope="col">S/N</th>
          <th class="text-center" scope="col">Task</th>
          <th class="text-center" scope="col">Status</th>
          <th class="text-center" scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {%for entry in todo_list%}
        {% if entry.completed %}
        <tr class="table-success">
          <th class="text-center" scope="row">{{forloop.counter}}</th>
          <td class="text-center">{{entry.item}}</td>
          <td class="text-center"> <a href="{% url 'dashboard:uncross' entry.id %}">Done</a> </td>
          <td class="text-center"><a href="{% url 'dashboard:delete' entry.id %}">Remove</a></td>
        </tr>
        {%else%}
        <tr class="table-danger">
          <td class="text-center" scope="row">{{forloop.counter}}</th>
          <td class="text-center">{{entry.item}}</td>
          <td class="text-center"><a href="{% url 'dashboard:cross' entry.id %}">Ongoing</a></td>
          <td class="text-center"><a href="{% url 'dashboard:delete' entry.id %}">Remove</a></td>
        </tr>
        {%endif%}
        {%endfor%}
      </tbody>
    </table>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="todoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create New Entry</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'dashboard:index' %}" method="POST">
          {% csrf_token %}
          {{ todo_form.item}}
          <button type="submit" class="btn btn-block btn-primary">Add Entry</button>
        </form>
      </div>
    </div>
  </div>



  <!-- ITEM 6  -->
  <div class="item six">
    <h3>Events Calendar</h3>

    <div class="cal-icon"><a href="/calendar">
        <i class="far fa-calendar-alt fa-10x"></i>
      </a>
    </div>
    <div>
      <h4>Checkout your latest events here</h4>
    </div>
  </div>



  {%endblock%}